# Generated by Django 3.1.1 on 2020-10-05 02:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BigmatchGroup',
            fields=[
                ('seq', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('reg_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EPLGroup',
            fields=[
                ('seq', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('reg_date', models.DateTimeField(auto_now_add=True)),
                ('del_yn', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='EPL',
            fields=[
                ('seq', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('EPL', 'EPL'), ('EFL', 'EFL'), ('리그1', '리그1')], max_length=10)),
                ('reg_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateField(blank=True)),
                ('del_yn', models.BooleanField(default=False)),
                ('score', models.IntegerField(blank=True)),
                ('win', models.IntegerField(blank=True)),
                ('draw', models.IntegerField(blank=True)),
                ('lose', models.IntegerField(blank=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yoonproject.eplgroup')),
            ],
        ),
        migrations.CreateModel(
            name='Bigmatch',
            fields=[
                ('seq', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('url', models.CharField(max_length=100)),
                ('memo', models.TextField()),
                ('reg_date', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yoonproject.bigmatchgroup')),
            ],
        ),
    ]
