# Generated by Django 3.1.1 on 2020-09-28 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yoonproject', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='epl',
            name='draw',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='epl',
            name='lose',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='epl',
            name='score',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='epl',
            name='win',
            field=models.IntegerField(null=True),
        ),
    ]
