# Generated by Django 3.1.1 on 2020-10-05 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yoonproject', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='epl',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
