# Generated by Django 3.1.1 on 2020-09-29 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yoonproject', '0003_auto_20200928_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='epl',
            name='status',
            field=models.CharField(choices=[('리그1', '리그1'), ('EPL', 'EPL'), ('EFL', 'EFL')], max_length=10),
        ),
    ]
