# Generated by Django 3.1.1 on 2020-09-29 01:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yoonproject', '0004_auto_20200929_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='epl',
            name='group',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='epl',
            name='status',
            field=models.ForeignKey(choices=[('리그1', '리그1'), ('EPL', 'EPL'), ('EFL', 'EFL')], on_delete=django.db.models.deletion.CASCADE, to='yoonproject.eplgroup'),
        ),
    ]
