# Generated by Django 3.1.1 on 2020-09-29 01:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yoonproject', '0005_auto_20200929_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='epl',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yoonproject.eplgroup'),
        ),
        migrations.AlterField(
            model_name='epl',
            name='status',
            field=models.CharField(choices=[('EPL', 'EPL'), ('EFL', 'EFL'), ('리그1', '리그1')], max_length=10),
        ),
    ]
