# Generated by Django 3.1.1 on 2020-09-29 02:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yoonproject', '0006_auto_20200929_1038'),
    ]

    operations = [
        migrations.CreateModel(
            name='EPLStatusGroup',
            fields=[
                ('seq', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('reg_date', models.DateTimeField(auto_now_add=True)),
                ('del_yn', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='epl',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yoonproject.eplstatusgroup'),
        ),
    ]
