# Generated by Django 3.1.1 on 2020-09-29 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yoonproject', '0007_auto_20200929_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='epl',
            name='status',
            field=models.CharField(max_length=50),
        ),
    ]
